Setup CORS
lindy-labs/sc_ethereum-backend pull request #20
Opened 2022-04-27 14:08 UTC by joaop21

This PR:
- adds CORS setup;
- adds API error handling and monitoring;

Before making this PR open for reviews, I left some comments about another possible options for CORS configuration. If you think it's worth to include some of them please comment below!

2022-04-28 21:41 UTC, gabrielpoca commented on src/api/index.ts
> +  origin: process.env.FRONTEND_URL,
can we do something simpler? For instance, in NODE_ENV development use `*` and otherwise use a regular expression that matches "*.sandclock.org"?

2022-05-02 11:06 UTC, joaop21 commented on src/api/index.ts
> +  origin: process.env.FRONTEND_URL,
Yes, it might be straightforward and simpler than adding an environment variable and having to set up another thing.
I'll change it 👍

2022-05-02 11:15 UTC, 0xrin1 requested changes
lgtm tbh, left a couple small comments

2022-05-02 11:15 UTC, 0xrin1 commented on src/api/index.ts
> +  // hideOptionsRoute: hide options route from the documentation built using fastify-swagger (default: true).
imo we can do without the option comments

2022-05-02 11:15 UTC, 0xrin1 commented on src/api/index.ts
> +  if (statusCode! >= 500) Monitoring.captureException(error);
there's an npm library we can use to make the http errors more legible

https://github.com/ShogunPanda/http-errors-enhanced/blob/main/src/errors.ts#L352

`yarn add http-errors-enhanced`

not necessary but IMO its nicer than having a bunch of literals scattered around

2022-05-02 13:42 UTC, joaop21 commented on src/api/index.ts
> +  // hideOptionsRoute: hide options route from the documentation built using fastify-swagger (default: true).
Yes, I left the options as comments here in the draft version so we can discuss if we could add some of them.
I'll remove them before this is ready for review 👍

2022-05-02 13:58 UTC, joaop21 commented on src/api/index.ts
> +  if (statusCode! >= 500) Monitoring.captureException(error);
Yes, I understand your point and I agree with it! But we have a small backend with simple endpoints, therefore I don't know if adding a dependency for it is worth it for our case.

Btw, I implement that error handler just so we could monitor internal server errors. It should be as simple as that.

2022-05-02 14:42 UTC, 0xrin1 approved these changes

2022-05-02 15:47 UTC, gabrielpoca commented on src/api/index.ts
> +  if (statusCode! >= 500) Monitoring.captureException(error);
Yap, I think this is fine because it's contained to this function

2022-05-02 15:48 UTC, gabrielpoca commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
What's this?

2022-05-02 15:48 UTC, gabrielpoca commented on src/api/index.ts
> +  reply.send(statusCode! >= 500 ? 'Internal server error' : error.message);
Why? Also, I think that in production you always want to return `Internal server error`, otherwise we may leak important information by mistake. And in dev you always want error.message because we want to give feedback to the developer

2022-05-02 16:24 UTC, joaop21 commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
I'm not sure what line are you talking about, so I'm assuming it's the 20th 😕
If a strange error pops up in the middle of the execution of any endpoint handler, the error appears with no `statusCode`. In this case, it's not an expected error, so we set it to 500. Otherwise, if it is an expected error and already set in the handler, then we keep it unchanged.

2022-05-02 16:27 UTC, joaop21 commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
For now, we don't have any case where we reply with 400s error codes, so this might be strange I have to agree.

2022-05-02 16:36 UTC, joaop21 commented on src/api/index.ts
> +  reply.send(statusCode! >= 500 ? 'Internal server error' : error.message);
Yes, in production we shouldn't return internal system messages. I have to change this!
Again, not sure what the "why?" was referring to 😕

2022-05-03 14:35 UTC, gabrielpoca commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
Ok, but in that case you don't need this https://github.com/lindy-labs/sc_ethereum-backend/pull/20/files#diff-764761d79ed791ea154187526b088322dba3bebe94f9d38ab22120554aba77c7R24 and you can I guess take this https://github.com/lindy-labs/sc_ethereum-backend/pull/20/files#diff-764761d79ed791ea154187526b088322dba3bebe94f9d38ab22120554aba77c7R27 out as well right?

2022-05-04 09:15 UTC, joaop21 commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
I can remove the first one, but the second I can't, otherwise, no response is sent back to the client and a promise will remain unfulfilled.

2022-05-04 09:15 UTC, joaop21 commented on src/api/index.ts
> +  const statusCode = error.statusCode! >= 400 ? error.statusCode : 500;
I can remove the first one, but the second I can't, otherwise, no response is sent back to the client and a promise will remain unfulfilled.

2022-05-04 13:28 UTC, gabrielpoca approved these changes

2022-05-04 13:45 UTC, merged